# Generated by Django 5.2.17 on 2026-09-28 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Videojuego',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('stock', models.IntegerField()),
                ('consola', models.CharField(max_length=100)),
                ('Estado', models.CharField(max_length=50)),
                ('ano', models.IntegerField()),
                ('PEGI', models.CharField(max_length=10)),
                ('descripcion', models.TextField()),
                ('precio', models.CharField(max_length=20)),
                ('imagen', models.CharField(max_length=300)),
            ],
        ),
    ]
