# Generated by Django 5.2.17 on 2026-09-29 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videojuegos', '0002_cargar_videojuegos_iniciales'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videojuego',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='images/videojuegos/'),
        ),
    ]
